### ISSUE TITLE
Сообщения повторяются

### ISSUE THREAD

**Issue by dulingleb** [iSa1vatore/vk-callback-bot#1]
Приветствую.
Столкнулся с такой проблемой: вот ввожу в чате например команду, она срабатывает. Но потом через какое-то время, она может опять сработать, хотя в чате я ее уже не вводил, бывает и другая срабатывает. Что может быть.
Заранее спасибо!

```
switch ($bot->event) {
    case 'message_new':
        //Обрабатывает сообщение пользователя и вводит нужные переменные.
        $bot->MessageProcessing();
        switch ($bot->command) {
            case 'start':
            case 'начать':
            case '/start':
                command_start($bot);
                break;
			case 'survey':
				command_survey($bot);
				break;
            default:
                $bot->message
                    ->text("Команда не найдена.")
                    ->send();
                break;
        }

    break;

    case 'confirmation':
        exit($bot->confirmation_key);
        break;
} 
$bot->sendOK();
```

**Comment by iSa1vatore** [comment]
Сервер не отправляет VK ответ "OK", и идет повторный запрос, возможно PHP кидает какой-то notice в вывод, посмотри что возвращает твой сервер.
"Настройки -> Работа с API -> Callback API -> Запросы" там нажми на отправленные и чекни неудавшиеся.
